### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [alfrcr/paginathing#9]
No license at all means "all rights reserved", means "no rights at all". I have modified your code to be pure JS and would like to use it in LibreOffice's help. Unfortunately, no license means I cannot do it.
The plugin you got inspiration from uses Apache 2.0: http://esimakin.github.io/twbs-pagination/#license so I guess you could use it as well.

So you can include a LICENSE file like so: https://github.com/krisk/Fuse/blob/master/LICENSE
...and a mention in the .js file header like so: https://github.com/krisk/Fuse/blob/master/dist/fuse.js

Thank you in advance.

**Comment by alfrcr** [comment]
Thanks for submitting this issue. I've added the license and it's MIT.
I am really excited that my plugin is used on a popular project.
Feel free to modify the code.

**Comment by ilmari-lauhakangas** [comment]
Thank you very much :) I will mention you in the release notes.
